fn_call_width = 100
fn_params_layout = "Vertical"
hard_tabs = true
max_width = 120
merge_derives = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = false

unstable_features = true
blank_lines_upper_bound = 2
brace_style = "AlwaysNextLine"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
empty_item_single_line = false
force_multiline_blocks = true
group_imports = "StdExternalCrate"
hex_literal_case = "Preserve"
match_arm_blocks = true
imports_granularity = "Item"
reorder_impl_items = true
